// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6lk40DjcXu5Ao7lkZmvtHlh1SGmqZ4Ic',
    appId: '1:832233370722:web:1d7fd54ea4aedadb968d3b',
    messagingSenderId: '832233370722',
    projectId: 'chatapp-7412e',
    authDomain: 'chatapp-7412e.firebaseapp.com',
    storageBucket: 'chatapp-7412e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0e_SSFfdqxMFSpW8JfyuJQ-vcnjhrkRM',
    appId: '1:832233370722:android:8261c4b98290d160968d3b',
    messagingSenderId: '832233370722',
    projectId: 'chatapp-7412e',
    storageBucket: 'chatapp-7412e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTm06AqWRHwpYj1BiJxCmAKa9rHVR5YtU',
    appId: '1:832233370722:ios:1fd3c75cc957a0af968d3b',
    messagingSenderId: '832233370722',
    projectId: 'chatapp-7412e',
    storageBucket: 'chatapp-7412e.appspot.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTm06AqWRHwpYj1BiJxCmAKa9rHVR5YtU',
    appId: '1:832233370722:ios:83c7bf32b115b57e968d3b',
    messagingSenderId: '832233370722',
    projectId: 'chatapp-7412e',
    storageBucket: 'chatapp-7412e.appspot.com',
    iosBundleId: 'com.example.main.RunnerTests',
  );

  // static const firebaseOptions = FirebaseOptions(
  //   appId: 'your_app_id',
  //   apiKey: 'your_api_key',
  //   projectId: 'chatapp-7412e',
  //   messagingSenderId: '832233370722',
  //   // authDomain: 'your_auth_domain',
  // );
}
